apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    name: consumer-service
    app: store-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31081
  selector:
    name: consumer-pod
    app: store-app