apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-service
    app: store-app
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 31092
  selector:
    name: kafka-pod
    app: store-app