#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-pod
      app: store-app
  template:
    metadata:
      name: kafka-pod
      labels:
        name: kafka-pod
        app: store-app
    spec:
      hostname: kafka-service
      containers:
        - name: kafka-service
          image: wurstmeister/kafka
          imagePullPolicy: Never
          ports:
            - containerPort: 9092
          env:
#            - name: KAFKA_ADVERTISED_HOST_NAME
#              value: kafka-service
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CREATE_TOPICS
              value: "test:1:1,order-events:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_BROKER_ID
              value: "1"
#             - name: KAFKA_ADVERTISED_PORT
#              value: "9092"