apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-service
    app: store-app
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31111
  selector:
    name: mysql-pod
    app: store-app