#apiVersion: v1
#kind: Pod
#metadata:
#  name: producer-pod
#  labels:
#    name: producer-pod
#    app: store-app
#spec:
#  hostname: producer
#  containers:
#    - name: store
#      image: jordanec/store-producer:latest
#      imagePullPolicy: Never
#      ports:
#        - containerPort: 8080
#      env:
#        - name: SPRING_PROFILES_ACTIVE
#          value: dockerFormik
