apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    name: producer-service
    app: store-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31080
  selector:
    name: producer-pod
    app: store-app