apiVersion: v1
kind: Service
metadata:
  name: store-web
  labels:
    name: store-web-service
    app: store-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31042
  selector:
    name: store-web-pod
    app: store-app