apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-web-deployment
  labels:
    app: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: store-web-pod
      app: store-app
  template:
    metadata:
      name: store-web-pod
      labels:
        name: store-web-pod
        app: store-app
    spec:
      hostname: store-web
      containers:
        - name: store-web
          image: jordanec/store-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80